import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const appSans = localFont({
  src: "../public/fonts/Bhineka-Regular.ttf",
  variable: "--font-geist-sans",
  display: "swap",
});

const appMono = localFont({
  src: "../public/fonts/Pixellettersfull-BnJ5.ttf",
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${appSans.variable} ${appMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
